export const LESSONs = [
    {
        id: 1,
        name: "Installation and Setup",
        shortDescription: "Learn how to set up your development environment for React.",
        content: "In this lesson, we will cover the installation of Node.js, npm, and create-react-app. You will learn how to set up your first React application and understand the project structure.",
        slug: "installation-setup",
        lesson_type: "text",
        image: "https://example.com/images/react-intro.jpg",
        thumb: "https://example.com/images/react-intro-thumb.jpg",
        tags: ["React", "JavaScript", "Frontend"],
        category: "Frontend Development",
        icon: "",
        state: "published",
        duration: "2 hours",
        configs: { },
        extends: { prerequisites: "Basic HTML and CSS knowledge" },
        hiddenContent: { notes: "Includes quizzes and exercises" },
        created_at: new Date("2023-01-01"),
        updated_at: new Date("2023-02-01"),
        created_by: "Jane Smith",
        ref_link: "https://reactjs.org/docs/getting-started.html",
        ref_link_type: "external",
    },
    {
        id: 2,
        name: "Components and Props",
        shortDescription: "Understand the building blocks of React applications.",
        content: "This lesson introduces you to components, the core building blocks of React applications. You will learn how to create functional and class components, and how to pass data using props.",
        slug: "components-props",
        lesson_type: "video",
        video_url: "https://example.com/videos/react-components.mp4",
        tags: ["React", "Components", "Props"],
        category: "Frontend Development",
        icon: "",
        state: "published",
        duration: "3 hours",
        configs: { },
        extends: { prerequisites: "Installation and Setup" },
        hiddenContent: { notes: "Includes code examples" },
        created_at: new Date("2023-01-15"),
        updated_at: new Date("2023-02-15"),
        created_by: "John Doe",
    },
    {
        id: 3,
        name: "State and Lifecycle",
        shortDescription: "Learn how to manage state in React components.",
        content: "In this lesson, you will learn about state management in React. We will cover the useState and useEffect hooks, and how to manage component lifecycle events.",
        slug: "state-lifecycle",
        lesson_type: "quiz",
        image: "https://example.com/images/react-state.jpg",
        thumb: "https://example.com/images/react-state-thumb.jpg",
        tags: ["React", "State", "Lifecycle"],
        category: "Frontend Development",
        icon: "",
        state: "published",
        duration: "2 hours",
        configs: { },
        extends: { prerequisites: "Components and Props" },
        hiddenContent: { notes: "Includes exercises" },
        created_at: new Date("2023-02-01"),
        updated_at: new Date("2023-03-01"),
        created_by: "Jane Smith",
    },
    {
        id: 4,
        name: "Handling Events",
        shortDescription: "Learn how to handle events in React applications.",
        content: "This lesson covers event handling in React. You will learn how to handle user inputs, form submissions, and other events using event handlers.",
        slug: "handling-events",
        lesson_type: "video",
        video_url: "https://example.com/videos/react-events.mp4",
        tags: ["React", "Events", "User Interaction"],
        category: "Frontend Development",
        icon: "",
        state: "published",
        duration: "2 hours",
        configs: { },
        extends: { prerequisites: "State and Lifecycle" },
        hiddenContent: { notes: "Includes quizzes" },
        created_at: new Date("2023-02-15"),
        updated_at: new Date("2023-03-15"),
        created_by: "John Doe",
    },
    {
        id: 5,
        name: "Conditional Rendering",
        shortDescription: "Learn how to render components conditionally in React.",
        content: "In this lesson, you will learn about conditional rendering in React. We will cover how to use if statements, ternary operators, and logical && operator for rendering components based on conditions.",
        slug: "conditional-rendering",
        lesson_type: "text",
        image: "https://example.com/images/react-conditional.jpg",
        thumb: "https://example.com/images/react-conditional-thumb.jpg",
        tags: ["React", "Conditional", "Rendering"],
        category: "Frontend Development",
        icon: "",
        state: "published",
        duration: "2 hours",
        configs: { },
        extends: { prerequisites: "Handling Events" },
        hiddenContent: { notes: "Includes exercises" },
        created_at: new Date("2023-03-01"),
        updated_at: new Date("2023-04-01"),
        created_by: "Jane Smith",
    },
    {
        id: 6,
        name: "Lists and Keys",
        shortDescription: "Learn how to render lists of data in React.",
        content: "This lesson covers how to render lists of data in React using the map function. You will also learn about the importance of keys in React and how to use them effectively.",
        slug: "lists-keys",
        lesson_type: "video",
        video_url: "https://example.com/videos/react-lists.mp4",
        tags: ["React", "Lists", "Keys"],
        category: "Frontend Development",
        icon: "",
        state: "published",
        duration: "2 hours",
        configs: { },
        extends: { prerequisites: "Conditional Rendering" },
        hiddenContent: { notes: "Includes code examples" },
        created_at: new Date("2023-03-15"),
        updated_at: new Date("2023-04-15"),
        created_by: "John Doe",
    },
    {
        id: 7,
        name: "Forms",
        shortDescription: "Learn how to handle forms in React applications.",
        content: "In this lesson, you will learn about controlled and uncontrolled components in React. We will cover how to handle form inputs, validation, and submission.",
        slug: "forms",
        lesson_type: "text",
        image: "https://example.com/images/react-forms.jpg",
        thumb: "https://example.com/images/react-forms-thumb.jpg",
        tags: ["React", "Forms", "User Input"],
        category: "Frontend Development",
        icon: "",
        state: "published",
        duration: "2 hours",
        configs: { },
        extends: { prerequisites: "Lists and Keys" },
        hiddenContent: { notes: "Includes exercises" },
        created_at: new Date("2023-04-01"),
        updated_at: new Date("2023-05-01"),
        created_by: "Jane Smith",
    },
    {
        id: 8,
        name: "Lifting State Up",
        shortDescription: "Learn how to lift state up in React applications.",
        content: "This lesson covers the concept of lifting state up in React. You will learn how to share state between components and manage it effectively.",
        slug: "lifting-state-up",
        lesson_type: "video",
        video_url: "https://example.com/videos/react-lifting-state.mp4",
        tags: ["React", "State", "Lifting"],
        category: "Frontend Development",
        icon: "",
        state: "published",
        duration: "2 hours",
        configs: { },
        extends: { prerequisites: "Forms" },
        hiddenContent: { notes: "Includes quizzes" },
        created_at: new Date("2023-04-15"),
        updated_at: new Date("2023-05-15"),
        created_by: "John Doe",
    }
]
