export const COURSES = [
    {
        _id: "652f3c2e4f1a2b3c4d5e6f7g", // Random MongoDB ObjectId
        name: "Introduction to JavaScript",
        description: "Learn the basics of JavaScript, the most popular programming language for web development.",
        slug: "introduction-to-javascript",
        course_type: "standard",
        image: "https://example.com/images/js-course.jpg",
        thumb: "https://example.com/images/js-thumb.jpg",
        tags: ["JavaScript", "Programming", "Web Development"],
        category: "Programming",
        icon: "https://example.com/icons/js-icon.png",
        icon_name: "lesson-finished",
        valid_from: new Date("2023-01-01"),
        valid_to: new Date("2023-12-31"),
        state: "released",
        difficulty: "beginner",
        duration: "4 weeks",
        configs: {  },
        extends: { prerequisites: "None" },
        hiddenContent: { notes: "Instructor-only materials" },
        lessons: [],
    },
    {
        _id: "652f3c2e4f1a2b3c4d5e6f8h", // Random MongoDB ObjectId
        name: "Advanced React Techniques",
        description: "Master advanced concepts and patterns in React to build scalable and high-performance applications.",
        slug: "advanced-react-techniques",
        course_type: "premium",
        image: "https://example.com/images/react-course.jpg",
        thumb: "https://example.com/images/react-thumb.jpg",
        tags: ["React", "Frontend", "Web Development"],
        category: "Frontend Development",
        icon: "https://example.com/icons/react-icon.png",
        icon_name: "lesson-inprogress",
        valid_from: new Date("2023-06-01"),
        valid_to: new Date("2024-05-31"),
        state: "reviewed",
        difficulty: "advanced",
        duration: "6 weeks",
        configs: { },
        extends: { prerequisites: "Basic React knowledge" },
        hiddenContent: { notes: "Includes bonus materials" },
        lessons: [],
    },
    {
        _id: "507f1f77bcf86cd799439011", // Random MongoDB ObjectId
        name: "Typescript",
        description: "Master advanced concepts and patterns in React to build scalable and high-performance applications.",
        slug: "advanced-react-techniques",
        course_type: "premium",
        image: "https://example.com/images/react-course.jpg",
        thumb: "https://example.com/images/react-thumb.jpg",
        tags: ["React", "Frontend", "Web Development"],
        category: "Frontend Development",
        icon: "https://example.com/icons/react-icon.png",
        icon_name: "lesson-ready",
        valid_from: new Date("2023-06-01"),
        valid_to: new Date("2024-05-31"),
        state: "reviewed",
        difficulty: "advanced",
        duration: "6 weeks",
        configs: { },
        extends: { prerequisites: "Basic React knowledge" },
        hiddenContent: { notes: "Includes bonus materials" },
        lessons: [],
    },
];