export const COURSES = [
    {
        _id: "652f3c2e4f1a2b3c4d5e6f7h", // Random MongoDB ObjectId
        name: "Welcome to the playground",
        shortDescription: "Playground overview, concept, purpose and target audience.",
        description: "Provide a brief overview of the playground and its purpose. This course is designed to help you understand the basics of the playground and how to navigate through it.",
        slug: "welcome-to-the-playground",
        course_type: "standard",
        image: "https://example.com/images/js-course.jpg",
        thumb: "https://example.com/images/js-thumb.jpg",
        tags: ["JavaScript", "Programming", "Web Development"],
        category: "Programming",
        icon: "https://example.com/icons/js-icon.png",
        icon_name: "lesson-finished",
        valid_from: new Date("2023-01-01"),
        valid_to: new Date("2023-12-31"),
        state: "finished",
        difficulty: "beginner",
        duration: "4 weeks",
        configs: {  },
        extends: { prerequisites: "None" },
        hiddenContent: { notes: "Instructor-only materials" },
        lessons: [],
        created_at: new Date("2023-01-01"),
        updated_at: new Date("2023-06-07"),
        created_by: "John Doe",
        num_learners: 745,
        num_certified_learners: 532,
        context: {
            user_id: 'abc',
            state: 'finished'
        },
        lessons: []
        },
        {
        _id: "652f3c2e4f1a2b3c4d5e6f8h", // Random MongoDB ObjectId
        name: "Explore existing prototypes",
        shortDescription: "This course provides a walkthrough of existing demos.",
        description: "Via various demos, you will learn how to use the playground and its features.",
        slug: "explore-existing-demos",
        course_type: "premium",
        image: "https://example.com/images/react-course.jpg",
        thumb: "https://example.com/images/react-thumb.jpg",
        tags: ["React", "Frontend", "Web Development"],
        category: "Frontend Development",
        icon: "https://example.com/icons/react-icon.png",
        icon_name: "lesson-inprogress",
        valid_from: new Date("2023-06-01"),
        valid_to: new Date("2024-05-31"),
        state: "learning",
        difficulty: "advanced",
        duration: "6 weeks",
        configs: { },
        extends: { prerequisites: "Basic React knowledge" },
        hiddenContent: { notes: "Includes bonus materials" },
        lessons: [],
        created_at: new Date("2023-01-02"),
        updated_at: new Date("2023-03-02"),
        created_by: "John Doe",
        num_learners: 500,
        num_certified_learners: 120,
        context: {
            user_id: 'abc',
            state: 'inprogress'
        },
        lessons: []
    },
    {
        _id: "652f3c2e4f1a2b3c4d5e6f9i", // Random MongoDB ObjectId
        name: "Register and login",
        shortDescription: "This course teaches you how to register and login.",
        description: "In this course you will learn how to register and login to the playground. You will also learn how to manage your profile.",
        slug: "register-and-login",
        course_type: "premium",
        image: "https://example.com/images/react-course.jpg",
        thumb: "https://example.com/images/react-thumb.jpg",
        tags: ["React", "Frontend", "Web Development"],
        category: "Frontend Development",
        icon: "https://example.com/icons/react-icon.png",
        icon_name: "lesson-ready",
        valid_from: new Date("2023-06-01"),
        valid_to: new Date("2024-05-31"),
        state: "locked",
        difficulty: "advanced",
        duration: "6 weeks",
        configs: { },
        extends: { prerequisites: "Basic React knowledge" },
        hiddenContent: { notes: "Includes bonus materials" },
        lessons: [],
        created_at: new Date("2024-04-03"),
        updated_at: new Date("2024-06-06"),
        created_by: "John Doe",
        num_learners: 453,
        num_certified_learners: 87,
        context: {
            user_id: 'abc',
            state: 'ready'
        },
        lessons: []
    },
    {
        _id: "507f1f77bcf86cd799439011", // Random MongoDB ObjectId
        name: "Vehicle Model and Vehicle API",
        shortDescription: "This course teaches you how to create a vehicle model.",
        description: "In this course your will learn how to create a vehicle model using the playground. You will learn about the different components of a vehicle model and how to use them effectively.",
        slug: "create-vehicle-model",
        course_type: "premium",
        image: "https://example.com/images/react-course.jpg",
        thumb: "https://example.com/images/react-thumb.jpg",
        tags: ["React", "Frontend", "Web Development"],
        category: "Frontend Development",
        icon: "https://example.com/icons/react-icon.png",
        icon_name: "lesson-ready",
        valid_from: new Date("2023-06-01"),
        valid_to: new Date("2024-05-31"),
        state: "locked",
        difficulty: "advanced",
        duration: "6 weeks",
        configs: { },
        extends: { prerequisites: "Basic React knowledge" },
        hiddenContent: { notes: "Includes bonus materials" },
        lessons: [],
        created_at: new Date("2024-04-03"),
        updated_at: new Date("2024-06-06"),
        created_by: "John Doe",
        num_learners: 453,
        num_certified_learners: 87,
        context: {
            user_id: 'abc',
            state: 'ready'
        },
        lessons: []
    },
    {
        _id: "507f1f77bcf86cd799439012", // Random MongoDB ObjectId
        name: "Create your first prototype",
        shortDescription: "This course teaches you how to create a simple prototype.",
        description: "In this course you will learn how to create a prototype using the playground. You will learn about the different components of a prototype and how to use them effectively.",
         slug: "create-prototype",
        course_type: "premium",
        image: "https://example.com/images/react-course.jpg",
        thumb: "https://example.com/images/react-thumb.jpg",
        tags: ["React", "Frontend", "Web Development"],
        category: "Frontend Development",
        icon: "https://example.com/icons/react-icon.png",
        icon_name: "lesson-ready",
        valid_from: new Date("2023-06-01"),
        valid_to: new Date("2024-05-31"),
        state: "locked",
        difficulty: "advanced",
        duration: "6 weeks",
        configs: { },
        extends: { prerequisites: "Basic React knowledge" },
        hiddenContent: { notes: "Includes bonus materials" },
        lessons: [],
        created_at: new Date("2024-04-03"),
        updated_at: new Date("2024-06-06"),
        created_by: "John Doe",
        num_learners: 453,
        num_certified_learners: 87,
        context: {
            user_id: 'abc',
            state: 'ready'
        },
        lessons: []
    },
    {
        _id: "507f1f77bcf86cd799439013", // Random MongoDB ObjectId
        name: "Create and manage wishlist API",
        shortDescription: "This course teaches you how to create and manage your own API.",
        description: "In this course you will learn how to create and manage your own API using the playground. You will learn about the different components of an API and how to use them effectively.",
        slug: "create-and-manage-api",
        course_type: "premium",
        image: "https://example.com/images/react-course.jpg",
        thumb: "https://example.com/images/react-thumb.jpg",
        tags: ["React", "Frontend", "Web Development"],
        category: "Frontend Development",
        icon: "https://example.com/icons/react-icon.png",
        icon_name: "lesson-ready",
        valid_from: new Date("2023-06-01"),
        valid_to: new Date("2024-05-31"),
        state: "locked",
        difficulty: "advanced",
        duration: "6 weeks",
        configs: { },
        extends: { prerequisites: "Basic React knowledge" },
        hiddenContent: { notes: "Includes bonus materials" },
        lessons: [],
        created_at: new Date("2024-04-03"),
        updated_at: new Date("2024-06-06"),
        created_by: "John Doe",
        num_learners: 453,
        num_certified_learners: 87,
        context: {
            user_id: 'abc',
            state: 'ready'
        },
        lessons: []
    },
    {
        _id: "507f1f77bcf86cd799439014", // Random MongoDB ObjectId
        name: "Collect Vehicle API Badge",
        shortDescription: "You are now ready to get your Vehicle API badge.",
        description: "Collect your Vehicle API badge and show it off to the world!",
        slug: "get-vehicle-api-badge",
        course_type: "premium",
        image: "https://example.com/images/react-course.jpg",
        thumb: "https://example.com/images/react-thumb.jpg",
        tags: ["React", "Frontend", "Web Development"],
        category: "Frontend Development",
        icon: "https://example.com/icons/react-icon.png",
        icon_name: "badge_1",
        valid_from: new Date("2023-06-01"),
        valid_to: new Date("2024-05-31"),
        state: "locked-highlight",
        difficulty: "advanced",
        duration: "6 weeks",
        configs: { },
        extends: { prerequisites: "Basic React knowledge" },
        hiddenContent: { notes: "Includes bonus materials" },
        lessons: [],
        created_at: new Date("2024-04-03"),
        updated_at: new Date("2024-06-06"),
        created_by: "John Doe",
        num_learners: 453,
        num_certified_learners: 87,
        context: {
            user_id: 'abc',
            state: 'ready'
        },
        lessons: []
    },
    {
        _id: "507f1f77bcf86cd799439015", // Random MongoDB ObjectId
        name: "Design dashboard and run prototype",
        shortDescription: "Build dashboard to present your idea and execute the demo.",
        description: "In this course you will learn how to design a dashboard and run the demo. You will learn about the different components of a dashboard and how to use them effectively.",
        slug: "design-dashboard",
        course_type: "premium",
        image: "https://example.com/images/react-course.jpg",
        thumb: "https://example.com/images/react-thumb.jpg",
        tags: ["React", "Frontend", "Web Development"],
        category: "Frontend Development",
        icon: "https://example.com/icons/react-icon.png",
        icon_name: "lesson-ready",
        valid_from: new Date("2023-06-01"),
        valid_to: new Date("2024-05-31"),
        state: "locked",
        difficulty: "advanced",
        duration: "6 weeks",
        configs: { },
        extends: { prerequisites: "Basic React knowledge" },
        hiddenContent: { notes: "Includes bonus materials" },
        lessons: [],
        created_at: new Date("2024-04-03"),
        updated_at: new Date("2024-06-06"),
        created_by: "John Doe",
        num_learners: 453,
        num_certified_learners: 87,
        context: {
            user_id: 'abc',
            state: 'ready'
        },
        lessons: []
    },
    {
        _id: "507f1f77bcf86cd799439016", // Random MongoDB ObjectId
        name: "Get Certificate",
        shortDescription: "Get your certification and show it off to the world!",
        description: "Congratulations! You have completed the course and are now ready to get your certification.",
        slug: "get-certificate",
        course_type: "premium",
        image: "https://example.com/images/react-course.jpg",
        thumb: "https://example.com/images/react-thumb.jpg",
        tags: ["React", "Frontend", "Web Development"],
        category: "Frontend Development",
        icon: "https://example.com/icons/react-icon.png",
        icon_name: "certificate",
        valid_from: new Date("2023-06-01"),
        valid_to: new Date("2024-05-31"),
        state: "locked-highlight",
        difficulty: "advanced",
        duration: "6 weeks",
        configs: { },
        extends: { prerequisites: "Basic React knowledge" },
        hiddenContent: { notes: "Includes bonus materials" },
        lessons: [],
        created_at: new Date("2024-04-03"),
        updated_at: new Date("2024-06-06"),
        created_by: "John Doe",
        num_learners: 453,
        num_certified_learners: 87,
        context: {
            user_id: 'abc',
            state: 'ready'
        },
        lessons: []
    },
];
