import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Learning Journey",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`h-screen w-screen overflow-y-auto ${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* <div className="w-full h-20 bg-slate-500 text-white flex items-center justify-center">I am header </div> */}
        {children}
      </body>
    </html>
  );
}
