export const LESSONs = [
    {
        id: 1,
        name: "Text lesson",
        shortDescription: "This is a sample of rich text lesson.",
        content: "In this lesson, we will cover the installation of Node.js, npm, and create-react-app. You will learn how to set up your first React application and understand the project structure.",
        slug: "installation-setup",
        lesson_type: "text",
        image: "https://example.com/images/react-intro.jpg",
        thumb: "https://example.com/images/react-intro-thumb.jpg",
        tags: ["React", "JavaScript", "Frontend"],
        category: "Frontend Development",
        icon: "",
        state: "published",
        duration: "2 hours",
        configs: { },
        extends: { prerequisites: "Basic HTML and CSS knowledge" },
        hiddenContent: { notes: "Includes quizzes and exercises" },
        created_at: new Date("2023-01-01"),
        updated_at: new Date("2023-02-01"),
        created_by: "Jane Smith",
        ref_link: "https://reactjs.org/docs/getting-started.html",
        ref_link_type: "external",
    },
    {
        id: 2,
        name: "Video lesson",
        shortDescription: "This is a sample of video lesson.",
        content: "This course introduces you how a video lesson works.",
        slug: "video-lesson",
        lesson_type: "video",
        video_url: "https://example.com/videos/react-components.mp4",
        tags: ["React", "Components", "Props"],
        category: "Frontend Development",
        icon: "",
        state: "published",
        duration: "3 hours",
        configs: { },
        extends: { prerequisites: "Installation and Setup" },
        hiddenContent: { notes: "Includes code examples" },
        created_at: new Date("2023-01-15"),
        updated_at: new Date("2023-02-15"),
        created_by: "John Doe",
    },
    {
        id: 3,
        name: "Quiz",
        shortDescription: "This is a sample of quiz lesson.",
        content: "This lesson demonstrates how a quiz works.",
        slug: "quiz-test",
        lesson_type: "quiz",
        image: "https://example.com/images/react-state.jpg",
        thumb: "https://example.com/images/react-state-thumb.jpg",
        tags: ["React", "State", "Lifecycle"],
        category: "Frontend Development",
        icon: "",
        state: "published",
        duration: "2 hours",
        configs: { },
        extends: { prerequisites: "Components and Props" },
        hiddenContent: { notes: "Includes exercises" },
        created_at: new Date("2023-02-01"),
        updated_at: new Date("2023-03-01"),
        created_by: "Jane Smith",
    },
    {
        id: 4,
        name: "Interactive lesson",
        shortDescription: "This is a sample of interactive lesson.",
        content: "Interactive lessons allow you to engage with the content in a hands-on way. This lesson will guide you with real code editor or interact with real tool.",
        slug: "interactive-lesson",
        lesson_type: "text",
        video_url: "https://example.com/videos/react-lifting-state.mp4",
        tags: ["React", "State", "Lifting"],
        category: "Frontend Development",
        icon: "",
        state: "published",
        duration: "2 hours",
        configs: { },
        extends: { prerequisites: "Forms" },
        hiddenContent: { notes: "Includes quizzes" },
        created_at: new Date("2023-04-15"),
        updated_at: new Date("2023-05-15"),
        created_by: "John Doe",
    }
]
